apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice2-contract
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice2-contract
  template:
    metadata:
      labels:
        app: microservice2-contract
    spec:
      containers:
        - name: microservice2-contract
          image: aminabakkali/microservice2-contract
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: microservice2-contract
spec:
  type: LoadBalancer
  selector:
    app: microservice2-contract
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083